name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies for client
      run: |
        cd book-request/client
        npm ci

    - name: Build React app
      run: |
        cd book-request/client
        npm run build

    - name: Deploy React app to /var/www/html
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -R book-request/client/dist/* /var/www/html/

    - name: Install dependencies for server
      run: |
        cd book-request/server
        npm ci

    - name: Restart Express server with PM2
      run: |
        pm2 restart /home/ubuntu/book-request/server
